import { registerAuthIpcHandlers } from './authIpc';
import { registerConfigIpcHandlers } from './configIpc';
import { registerModelIpcHandlers } from './modelIpc';
import { registerThemeIpcHandlers } from './themeIpc';
import { registerAiIpcHandlers } from './aiIpc';
import { registerIntranetIpcHandlers } from './intranetIpc';
import { registerApiIpcHandlers } from './apiIpc';
import { registerVideoIpcHandlers } from './videoIpc';
import { registerFfmpegIpcHandlers } from './ffmpegIpc';
import { registerCompressIpcHandlers } from './compressIpc';
import { registerDownloadIpcHandlers } from './downloadIpc';
import { registerSlideExtractionIpcHandlers } from './slideExtractionIpc';
import { registerOfflineIpcHandlers } from './offlineIpc';
import { registerDialogIpcHandlers } from './dialogIpc';
import { registerWindowIpcHandlers } from './windowIpc';
import { registerShellIpcHandlers } from './shellIpc';
import { registerMenuIpcHandlers } from './menuIpc';
import { registerPowerIpcHandlers } from './powerIpc';
import { registerCacheIpcHandlers } from './cacheIpc';
import { registerAppIpcHandlers } from './appIpc';
import { registerToolsWindowIpcHandlers } from './toolsWindowIpc';
import { registerYuketangIpcHandlers } from './yuketangIpc';
import { registerTrashIpcHandlers } from './trashIpc';
import { registerCropIpcHandlers } from './cropIpc';
import { registerPdfMakerIpcHandlers } from './pdfMakerIpc';
import { registerUpdateIpcHandlers } from './updateIpc';
import { registerQtExtractorIpcHandlers } from './qtExtractorIpc';
import { registerExtractorInstallerIpcHandlers } from './extractorInstallerIpc';
import type { IpcServices } from './types';

export function registerAllIpcHandlers(services: IpcServices): void {
  registerAuthIpcHandlers(services);
  registerConfigIpcHandlers(services);
  registerModelIpcHandlers(services);
  registerThemeIpcHandlers(services);
  registerAiIpcHandlers(services);
  registerIntranetIpcHandlers(services);
  registerApiIpcHandlers(services);
  registerVideoIpcHandlers(services);
  registerFfmpegIpcHandlers(services);
  registerCompressIpcHandlers(services);
  registerDownloadIpcHandlers(services);
  registerSlideExtractionIpcHandlers(services);
  registerOfflineIpcHandlers();
  registerDialogIpcHandlers();
  registerWindowIpcHandlers();
  registerShellIpcHandlers();
  registerMenuIpcHandlers();
  registerPowerIpcHandlers(services);
  registerCacheIpcHandlers();
  registerAppIpcHandlers();
  registerToolsWindowIpcHandlers(services);
  registerYuketangIpcHandlers(services);
  registerTrashIpcHandlers(services);
  registerCropIpcHandlers(services);
  registerPdfMakerIpcHandlers(services);
  registerUpdateIpcHandlers(services);
  registerQtExtractorIpcHandlers(services);
  registerExtractorInstallerIpcHandlers(services);
}

export type { IpcServices } from './types';
