import { ipcMain, BrowserWindow, dialog, app } from 'electron';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import type { PdfMakeOptions, FolderEntry, CoverPageInfo } from '@main/export/pdfService';
import {
  extractCourseName,
  extractSessionLabel,
  formatCoverTimestamp
} from '@main/export/coverFontService';
import enTranslations from '../../renderer/shared/i18n/locales/en.json';
import type { IpcServices } from './types';
import { createLogger } from '@main/infra/logger';
const log = createLogger('PdfMakerIpc');

type PdfMakerOutputMode = 'single' | 'batch';
type SlidesExportFormat = 'pdf' | 'pptx';
type PdfMakerRequestOptions = PdfMakeOptions & {
  outputMode?: PdfMakerOutputMode;
  outputFormat?: SlidesExportFormat;
  includeCover?: boolean;
  copyrightText?: string;
};

function buildCoverInfo(folderName: string, includeSession: boolean, copyrightText: string): CoverPageInfo {
  const courseName = extractCourseName(folderName);
  const sessionName = includeSession ? extractSessionLabel(folderName) : undefined;
  return {
    courseName: courseName || folderName,
    sessionName,
    copyrightText,
    footerText: `Generated by ${app.getName()} · ${formatCoverTimestamp(new Date())}`
  };
}

function expandHomePath(targetPath: string): string {
  return targetPath.startsWith('~')
    ? path.join(os.homedir(), targetPath.slice(1))
    : targetPath;
}

function getBatchExportBaseName(folderName: string): string {
  const rawName = folderName.startsWith('slides_') ? folderName : `slides_${folderName}`;
  const sanitized = rawName
    .replace(/[<>:"/\\|?*]/g, '_')
    .split('')
    .map(char => (char.charCodeAt(0) < 32 ? '_' : char))
    .join('')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/[. ]+$/g, '');

  if (!sanitized) return 'slides';
  if (/^(con|prn|aux|nul|com[1-9]|lpt[1-9])$/i.test(sanitized)) {
    return `_${sanitized}`;
  }
  return sanitized;
}

function getExportExtension(format: SlidesExportFormat): 'pdf' | 'pptx' {
  return format === 'pptx' ? 'pptx' : 'pdf';
}

function getExportLabel(format: SlidesExportFormat): 'PDF' | 'PPTX' {
  return format === 'pptx' ? 'PPTX' : 'PDF';
}

function getBatchDefaultFolderName(format: SlidesExportFormat): 'PDFs' | 'PPTXs' {
  return format === 'pptx' ? 'PPTXs' : 'PDFs';
}

function getUniqueExportPath(
  outputDir: string,
  baseName: string,
  extension: 'pdf' | 'pptx',
  usedNames: Set<string>
): string {
  let index = 1;
  let fileName = `${baseName}.${extension}`;

  while (
    usedNames.has(fileName.toLowerCase()) ||
    fs.existsSync(path.join(outputDir, fileName))
  ) {
    index++;
    fileName = `${baseName} (${index}).${extension}`;
  }

  usedNames.add(fileName.toLowerCase());
  return path.join(outputDir, fileName);
}

function makeSlidesExport(
  pdfService: IpcServices['pdfService'],
  format: SlidesExportFormat,
  folders: FolderEntry[],
  options: PdfMakeOptions,
  outputPath: string,
  onProgress?: (current: number, total: number) => void
) {
  return format === 'pptx'
    ? pdfService.makePptx(folders, options, outputPath, onProgress)
    : pdfService.makePdf(folders, options, outputPath, onProgress);
}

export function registerPdfMakerIpcHandlers(services: IpcServices): void {
  const { configService, windowManager, slideExtractionService, pdfService } = services;

  ipcMain.handle('pdfmaker:getFolders', async () => {
    try {
      const outputDir = configService.getConfig().outputDirectory;
      const expandedPath = outputDir.startsWith('~')
        ? path.join(os.homedir(), outputDir.slice(1))
        : outputDir;

      const entries = await fs.promises.readdir(expandedPath, { withFileTypes: true });
      const slideFolders = entries.filter(entry => entry.isDirectory() && entry.name.startsWith('slides_'));

      const folders = await Promise.all(
        slideFolders.map(async entry => {
          const folderPath = path.join(expandedPath, entry.name);
          let imageCount = 0;
          try {
            const files = await fs.promises.readdir(folderPath);
            imageCount = files.filter(f => f.startsWith('Slide_') && f.endsWith('.png')).length;
          } catch { /* folder unreadable — count stays 0 */ }
          return { name: entry.name, path: folderPath, imageCount };
        })
      );

      return folders;
    } catch (error) {
      log.error('Failed to get folders:', error);
      throw error;
    }
  });

  ipcMain.handle('pdfmaker:getImages', async (_event, folderPath: string) => {
    try {
      const entries = await fs.promises.readdir(folderPath, { withFileTypes: true });
      const images = entries
        .filter(entry => entry.isFile() && entry.name.startsWith('Slide_') && entry.name.endsWith('.png'))
        .map(entry => ({
          name: entry.name,
          path: path.join(folderPath, entry.name)
        }));
      return images;
    } catch (error) {
      log.error('Failed to get images:', error);
      throw error;
    }
  });

  ipcMain.handle('pdfmaker:getImageAsBase64', async (_event, imagePath: string) => {
    try {
      const buffer = await fs.promises.readFile(imagePath);
      return buffer.toString('base64');
    } catch (error) {
      log.error('Failed to read image:', error);
      throw error;
    }
  });

  ipcMain.handle('pdfmaker:deleteImage', async (_event, imagePath: string) => {
    try {
      const filename = path.basename(imagePath);
      const outputPath = path.dirname(imagePath);
      await slideExtractionService.moveToInAppTrash(outputPath, filename, {
        reason: 'manual',
        reasonDetails: 'User deleted via Results View'
      });
      return { success: true };
    } catch (error) {
      log.error('Failed to delete image:', error);
      throw error;
    }
  });

  ipcMain.handle('pdfmaker:makePdf', async (_event, folders: FolderEntry[], requestOptions: PdfMakerRequestOptions) => {
    try {
      const {
        outputMode = 'single',
        outputFormat = 'pdf',
        includeCover = false,
        copyrightText,
        ...options
      } = requestOptions;
      const extension = getExportExtension(outputFormat);
      const formatLabel = getExportLabel(outputFormat);
      const toolsWindow = windowManager.getToolsWindow();
      const parentWindow = toolsWindow || BrowserWindow.getFocusedWindow();
      const effectiveCopyright = copyrightText && copyrightText.trim().length > 0
        ? copyrightText
        : enTranslations.pdfmaker.coverCopyright;

      if (outputMode === 'batch') {
        const emptyFolder = folders.find(folder => folder.images.length === 0);
        if (emptyFolder) {
          return { success: false, error: `No images in folder: ${emptyFolder.name}` };
        }

        const totalImages = folders.reduce((sum, folder) => sum + folder.images.length, 0);
        if (totalImages === 0) {
          return { success: false, error: 'No images to process' };
        }

        const configuredOutputDir = expandHomePath(configService.getConfig().outputDirectory);
        const result = await dialog.showSaveDialog(parentWindow!, {
          title: `Choose ${formatLabel} Output Folder`,
          defaultPath: path.join(configuredOutputDir, getBatchDefaultFolderName(outputFormat)),
          buttonLabel: 'Use Folder',
          nameFieldLabel: 'Folder Name'
        });

        if (result.canceled || !result.filePath) {
          return { success: false, error: 'Cancelled' };
        }

        const outputDir = expandHomePath(result.filePath);
        await fs.promises.mkdir(outputDir, { recursive: true });

        const generatedPaths: string[] = [];
        const usedNames = new Set<string>();
        let processedBefore = 0;

        for (const folder of folders) {
          const outputPath = getUniqueExportPath(
            outputDir,
            getBatchExportBaseName(folder.name),
            extension,
            usedNames
          );

          const perFolderOptions: PdfMakeOptions = includeCover
            ? { ...options, cover: buildCoverInfo(folder.name, true, effectiveCopyright) }
            : options;

          const exportResult = await makeSlidesExport(
            pdfService,
            outputFormat,
            [folder],
            perFolderOptions,
            outputPath,
            (current) => {
              windowManager.getToolsWindow()?.webContents.send('pdfmaker:progress', {
                current: processedBefore + current,
                total: totalImages
              });
            }
          );

          if (!exportResult.success || !exportResult.path) {
            return {
              success: false,
              error: exportResult.error || `Failed to create ${formatLabel} for ${folder.name}`
            };
          }

          processedBefore += folder.images.length;
          generatedPaths.push(exportResult.path);
        }

        return {
          success: true,
          mode: 'batch',
          format: outputFormat,
          outputDir,
          paths: generatedPaths
        };
      }

      let defaultFileName = `slides.${extension}`;
      let singleCoverCourseName = '';
      if (folders.length > 0) {
        singleCoverCourseName = extractCourseName(folders[0].name);
        defaultFileName = `slides_${singleCoverCourseName}.${extension}`;
      }
      const result = await dialog.showSaveDialog(parentWindow!, {
        title: `Save ${formatLabel}`,
        defaultPath: path.join(
          configService.getConfig().outputDirectory,
          defaultFileName
        ),
        filters: [{ name: `${formatLabel} Files`, extensions: [extension] }]
      });

      if (result.canceled || !result.filePath) {
        return { success: false, error: 'Cancelled' };
      }

      const outputPath = result.filePath;

      const singleOptions: PdfMakeOptions = includeCover && folders.length > 0
        ? { ...options, cover: buildCoverInfo(folders[0].name, false, effectiveCopyright) }
        : options;

      const exportResult = await makeSlidesExport(
        pdfService,
        outputFormat,
        folders,
        singleOptions,
        outputPath,
        (current, total) => {
          windowManager.getToolsWindow()?.webContents.send('pdfmaker:progress', { current, total });
        }
      );

      if (!exportResult.success || !exportResult.path) {
        return exportResult;
      }

      return {
        success: true,
        mode: 'single',
        format: outputFormat,
        path: exportResult.path
      };
    } catch (error) {
      log.error('Failed to export slides:', error);
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error'
      };
    }
  });
}
