import type { MainAuthService } from '@main/platform/authService';
import type { ApiClient } from '@main/platform/apiClient';
import type { ConfigService } from '@main/platform/configService';
import type { IntranetMappingService } from '@main/platform/intranetMappingService';
import type { VideoProxyService } from '@main/video/videoProxyService';
import type { ThumbnailService } from '@main/video/thumbnailService';
import type { FFmpegService } from '@main/infra/ffmpegService';
import type { M3u8DownloadService } from '@main/video/m3u8DownloadService';
import type { PowerManagementService } from '@main/platform/powerManagementService';
import type { AIPromptsService } from '@main/ai/aiPromptsService';
import type { AIFilteringService } from '@main/ai/aiFilteringService';
import type { LLMApiService } from '@main/ai/llmApiService';
import type { UpdateDownloadService } from '@main/download/updateDownloadService';
import type { QtExtractorService } from '@main/extraction/qtExtractorService';
import type { ExtractorInstallerService } from '@main/download/extractorInstallerService';
import type { AutoCropModelService } from '@main/ai/autoCropModelService';
import type { MlClassifierModelService } from '@main/ai/mlClassifierModelService';
import type { CompressLectureService } from '@main/video/compressLectureService';
import type { WindowManager } from '@main/platform/windowManager';
import type { PdfService } from '@main/export/pdfService';
import type { NoteExportService } from '@main/export/noteExportService';
import type { SlideExtractionService } from '@main/extraction/slideExtractionService';
import type { SlideMetadataService } from '@main/extraction/slideMetadataService';
import type { OfflineProcessingService } from '@main/extraction/offlineProcessingService';
import type { CacheManagementService } from '@main/platform/cacheManagementService';
import type { NotesService } from '@main/platform/notesService';

export interface IpcServices {
  authService: MainAuthService;
  apiClient: ApiClient;
  configService: ConfigService;
  intranetMappingService: IntranetMappingService;
  videoProxyService: VideoProxyService;
  thumbnailService: ThumbnailService;
  ffmpegService: FFmpegService;
  m3u8DownloadService: M3u8DownloadService;
  powerManagementService: PowerManagementService;
  aiPromptsService: AIPromptsService;
  aiFilteringService: AIFilteringService;
  llmApiService: LLMApiService;
  updateDownloadService: UpdateDownloadService;
  qtExtractorService: QtExtractorService;
  extractorInstallerService: ExtractorInstallerService;
  autoCropModelService: AutoCropModelService;
  mlClassifierModelService: MlClassifierModelService;
  compressLectureService: CompressLectureService;
  windowManager: WindowManager;
  pdfService: PdfService;
  noteExportService: NoteExportService;
  slideExtractionService: SlideExtractionService;
  slideMetadataService: SlideMetadataService;
  offlineProcessingService: OfflineProcessingService;
  cacheManagementService: CacheManagementService;
  notesService: NotesService;
}
